version: "3.3"

services:
  ncard:
    image: chan0216/ncard
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Taipei
    ports:
      - "8000:8000"
    command: python app.py

  nginx:
    image: chan0216/nginx
    volumes:
      - ./certificate.crt:/etc/ssl/certificate.crt
      - ./private.key:/etc/ssl/private.key
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ncard
