version: "3.3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask
    container_name: flask
    environment:
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    networks:
      network:
        aliases:
          - flask
networks:
  network:
